name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - uses: mscoutermarsh/cowsays-action@master
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay