name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - uses: actions/setup-node@v3
        with:
          node-version: 1.0.0
      - run: npm install
      - run: npm run lint